<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WwdeCountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('wwde_countries')->insert([
            [
                'continent_id' => 4, // Europa
                'title' => 'Germany',
                'alias' => 'germany',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'country_code' => 'DE',
                'country_text' => 'Germany is a country in central Europe known for its rich history and culture.',
                'currency_conversion' => '1.0',
                'population' => 83166711,
                'capital' => 'Berlin',
                'population_capital' => 3644826,
                'area' => 357022,
                'official_language' => 'German',
                'language_ezmz' => 'German',
                'bsp_in_USD' => 45000,
                'life_expectancy_m' => 78.6,
                'life_expectancy_w' => 83.4,
                'population_density' => 233,
                'country_iso_3' => 'DEU',
                'continent_iso_2' => 'EU',
                'continent_iso_3' => 'EUR',
                'country_visum_needed' => false,
                'country_visum_max_time' => null,
                'count_climatezones' => 1,
                'climatezones_ids' => '1',
                'climatezones_lnam' => 'Temperate',
                'climatezones_details_lnam' => 'Moderate climate zone with cold winters and mild summers.',
                'artikel' => 'das',
                'travelwarning_id' => null,
                'price_tendency' => 'Medium',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'continent_id' => 4, // Europa
                'title' => 'France',
                'alias' => 'france',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'country_code' => 'FR',
                'country_text' => 'France is known for its art, cuisine, and iconic landmarks like the Eiffel Tower.',
                'currency_conversion' => '1.0',
                'population' => 67413000,
                'capital' => 'Paris',
                'population_capital' => 2140526,
                'area' => 551695,
                'official_language' => 'French',
                'language_ezmz' => 'French',
                'bsp_in_USD' => 41000,
                'life_expectancy_m' => 79.5,
                'life_expectancy_w' => 85.3,
                'population_density' => 122,
                'country_iso_3' => 'FRA',
                'continent_iso_2' => 'EU',
                'continent_iso_3' => 'EUR',
                'country_visum_needed' => false,
                'country_visum_max_time' => null,
                'count_climatezones' => 3,
                'climatezones_ids' => '1,2,3',
                'climatezones_lnam' => 'Temperate, Mediterranean',
                'climatezones_details_lnam' => 'Diverse climate zones with both temperate and Mediterranean regions.',
                'artikel' => 'das',
                'travelwarning_id' => null,
                'price_tendency' => 'Medium',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'continent_id' => 1, // Afrika
                'title' => 'South Africa',
                'alias' => 'south-africa',
                'currency_code' => 'ZAR',
                'currency_name' => 'Rand',
                'country_code' => 'ZA',
                'country_text' => 'South Africa is known for its diverse cultures, wildlife, and stunning landscapes.',
                'currency_conversion' => '0.06',
                'population' => 59308690,
                'capital' => 'Pretoria',
                'population_capital' => 741651,
                'area' => 1219090,
                'official_language' => '11 official languages',
                'language_ezmz' => 'English, Zulu, Afrikaans, others',
                'bsp_in_USD' => 12000,
                'life_expectancy_m' => 64.3,
                'life_expectancy_w' => 68.1,
                'population_density' => 49,
                'country_iso_3' => 'ZAF',
                'continent_iso_2' => 'AF',
                'continent_iso_3' => 'AFR',
                'country_visum_needed' => false,
                'country_visum_max_time' => null,
                'count_climatezones' => 4,
                'climatezones_ids' => '1,2,3,4',
                'climatezones_lnam' => 'Desert, Mediterranean, Subtropical, Temperate',
                'climatezones_details_lnam' => 'Diverse climate zones including deserts and subtropical regions.',
                'artikel' => 'das',
                'travelwarning_id' => null,
                'price_tendency' => 'Affordable',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'continent_id' => 5, // Nordamerika
                'title' => 'United States',
                'alias' => 'united-states',
                'currency_code' => 'USD',
                'currency_name' => 'Dollar',
                'country_code' => 'US',
                'country_text' => 'The United States is a country known for its global influence and diverse landscapes.',
                'currency_conversion' => '1.0',
                'population' => 331893745,
                'capital' => 'Washington, D.C.',
                'population_capital' => 692683,
                'area' => 9833520,
                'official_language' => 'English',
                'language_ezmz' => 'English',
                'bsp_in_USD' => 63000,
                'life_expectancy_m' => 76.3,
                'life_expectancy_w' => 81.4,
                'population_density' => 36,
                'country_iso_3' => 'USA',
                'continent_iso_2' => 'NA',
                'continent_iso_3' => 'NAM',
                'country_visum_needed' => true,
                'country_visum_max_time' => 90,
                'count_climatezones' => 6,
                'climatezones_ids' => '1,2,3,4,5,6',
                'climatezones_lnam' => 'Desert, Mediterranean, Subtropical, Temperate, Continental, Polar',
                'climatezones_details_lnam' => 'Wide range of climates from deserts to polar regions.',
                'artikel' => 'die',
                'travelwarning_id' => null,
                'price_tendency' => 'Expensive',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'continent_id' => 7, // Südamerika
                'title' => 'Brazil',
                'alias' => 'brazil',
                'currency_code' => 'BRL',
                'currency_name' => 'Real',
                'country_code' => 'BR',
                'country_text' => 'Brazil is known for its vibrant culture, Amazon rainforest, and beautiful beaches.',
                'currency_conversion' => '0.18',
                'population' => 213993437,
                'capital' => 'Brasília',
                'population_capital' => 3055149,
                'area' => 8515767,
                'official_language' => 'Portuguese',
                'language_ezmz' => 'Portuguese',
                'bsp_in_USD' => 7200,
                'life_expectancy_m' => 72.8,
                'life_expectancy_w' => 79.9,
                'population_density' => 25,
                'country_iso_3' => 'BRA',
                'continent_iso_2' => 'SA',
                'continent_iso_3' => 'SAM',
                'country_visum_needed' => false,
                'country_visum_max_time' => 90,
                'count_climatezones' => 5,
                'climatezones_ids' => '1,2,3,4,5',
                'climatezones_lnam' => 'Tropical, Subtropical, Desert, Savanna, Temperate',
                'climatezones_details_lnam' => 'Mostly tropical with diverse ecosystems.',
                'artikel' => 'das',
                'travelwarning_id' => null,
                'price_tendency' => 'Affordable',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'continent_id' => 6, // Ozeanien
                'title' => 'Australia',
                'alias' => 'australia',
                'currency_code' => 'AUD',
                'currency_name' => 'Australian Dollar',
                'country_code' => 'AU',
                'country_text' => 'Australia is known for its unique wildlife, stunning landscapes, and vibrant cities like Sydney and Melbourne.',
                'currency_conversion' => '0.65', // Beispiel-Wechselkurs
                'population' => 25788217,
                'capital' => 'Canberra',
                'population_capital' => 451000,
                'area' => 7692024,
                'official_language' => 'English',
                'language_ezmz' => 'English',
                'bsp_in_USD' => 50000,
                'life_expectancy_m' => 81.2,
                'life_expectancy_w' => 85.0,
                'population_density' => 3,
                'country_iso_3' => 'AUS',
                'continent_iso_2' => 'OC',
                'continent_iso_3' => 'OCE',
                'country_visum_needed' => false,
                'country_visum_max_time' => null,
                'count_climatezones' => 4,
                'climatezones_ids' => '1,2,3,4',
                'climatezones_lnam' => 'Tropical, Subtropical, Temperate, Arid',
                'climatezones_details_lnam' => 'Australia has a diverse range of climates, from tropical rainforests to arid deserts.',
                'artikel' => 'das',
                'travelwarning_id' => null,
                'price_tendency' => 'Medium',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'continent_id' => 6, // Ozeanien
                'title' => 'New Zealand',
                'alias' => 'new-zealand',
                'currency_code' => 'NZD',
                'currency_name' => 'New Zealand Dollar',
                'country_code' => 'NZ',
                'country_text' => 'New Zealand is famous for its breathtaking landscapes, including mountains, fiords, and geothermal areas.',
                'currency_conversion' => '0.60', // Beispiel-Wechselkurs
                'population' => 5132700,
                'capital' => 'Wellington',
                'population_capital' => 215000,
                'area' => 268021,
                'official_language' => 'English, Māori, New Zealand Sign Language',
                'language_ezmz' => 'English, Māori',
                'bsp_in_USD' => 40000,
                'life_expectancy_m' => 80.5,
                'life_expectancy_w' => 84.3,
                'population_density' => 18,
                'country_iso_3' => 'NZL',
                'continent_iso_2' => 'OC',
                'continent_iso_3' => 'OCE',
                'country_visum_needed' => false,
                'country_visum_max_time' => null,
                'count_climatezones' => 3,
                'climatezones_ids' => '1,2,3',
                'climatezones_lnam' => 'Temperate, Subtropical, Oceanic',
                'climatezones_details_lnam' => 'New Zealand has a mild, temperate climate with a variety of microclimates.',
                'artikel' => 'das',
                'travelwarning_id' => null,
                'price_tendency' => 'Medium',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'continent_id' => 6, // Ozeanien
                'title' => 'Fiji',
                'alias' => 'fiji',
                'currency_code' => 'FJD',
                'currency_name' => 'Fijian Dollar',
                'country_code' => 'FJ',
                'country_text' => 'Fiji is known for its stunning beaches, coral reefs, and friendly locals.',
                'currency_conversion' => '0.45', // Beispiel-Wechselkurs
                'population' => 926276,
                'capital' => 'Suva',
                'population_capital' => 177000,
                'area' => 18274,
                'official_language' => 'English, Fijian, Hindi',
                'language_ezmz' => 'English, Fijian',
                'bsp_in_USD' => 9000,
                'life_expectancy_m' => 69.8,
                'life_expectancy_w' => 73.6,
                'population_density' => 49,
                'country_iso_3' => 'FJI',
                'continent_iso_2' => 'OC',
                'continent_iso_3' => 'OCE',
                'country_visum_needed' => false,
                'country_visum_max_time' => null,
                'count_climatezones' => 2,
                'climatezones_ids' => '1,2',
                'climatezones_lnam' => 'Tropical, Subtropical',
                'climatezones_details_lnam' => 'Fiji has a tropical climate with warm temperatures year-round.',
                'artikel' => 'das',
                'travelwarning_id' => null,
                'price_tendency' => 'Affordable',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'continent_id' => 6, // Ozeanien
                'title' => 'Papua New Guinea',
                'alias' => 'papua-new-guinea',
                'currency_code' => 'PGK',
                'currency_name' => 'Papua New Guinean Kina',
                'country_code' => 'PG',
                'country_text' => 'Papua New Guinea is known for its diverse cultures, rainforests, and rugged terrain.',
                'currency_conversion' => '0.28', // Beispiel-Wechselkurs
                'population' => 9119000,
                'capital' => 'Port Moresby',
                'population_capital' => 364125,
                'area' => 462840,
                'official_language' => 'English',
                'language_ezmz' => 'English',
                'bsp_in_USD' => 2500,
                'life_expectancy_m' => 63.2,
                'life_expectancy_w' => 65.8,
                'population_density' => 19,
                'country_iso_3' => 'PNG',
                'continent_iso_2' => 'OC',
                'continent_iso_3' => 'OCE',
                'country_visum_needed' => true,
                'country_visum_max_time' => 30,
                'count_climatezones' => 3,
                'climatezones_ids' => '1,2,3',
                'climatezones_lnam' => 'Tropical, Subtropical, Highland',
                'climatezones_details_lnam' => 'Papua New Guinea has a tropical climate with high humidity and rainfall.',
                'artikel' => 'das',
                'travelwarning_id' => null,
                'price_tendency' => 'Affordable',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'continent_id' => 1, // Afrika
                'title' => 'Egypt',
                'alias' => 'egypt',
                'currency_code' => 'EGP',
                'currency_name' => 'Egyptian Pound',
                'country_code' => 'EG',
                'country_text' => 'Egypt is known for its ancient history, the Pyramids of Giza, and the Nile River.',
                'currency_conversion' => '0.032',
                'population' => 104124440,
                'capital' => 'Cairo',
                'population_capital' => 9121515,
                'area' => 1002450,
                'official_language' => 'Arabic',
                'language_ezmz' => 'Arabic',
                'bsp_in_USD' => 10000,
                'life_expectancy_m' => 71.8,
                'life_expectancy_w' => 74.9,
                'population_density' => 104,
                'country_iso_3' => 'EGY',
                'continent_iso_2' => 'AF',
                'continent_iso_3' => 'AFR',
                'country_visum_needed' => false,
                'country_visum_max_time' => null,
                'count_climatezones' => 2,
                'climatezones_ids' => '1,2',
                'climatezones_lnam' => 'Desert, Mediterranean',
                'climatezones_details_lnam' => 'Egypt has a desert climate with hot, dry summers and mild winters.',
                'artikel' => 'das',
                'travelwarning_id' => null,
                'price_tendency' => 'Affordable',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'continent_id' => 1, // Afrika
                'title' => 'Kenya',
                'alias' => 'kenya',
                'currency_code' => 'KES',
                'currency_name' => 'Kenyan Shilling',
                'country_code' => 'KE',
                'country_text' => 'Kenya is famous for its wildlife, national parks, and the Great Rift Valley.',
                'currency_conversion' => '0.008',
                'population' => 54580074,
                'capital' => 'Nairobi',
                'population_capital' => 4730000,
                'area' => 580367,
                'official_language' => 'English, Swahili',
                'language_ezmz' => 'Swahili',
                'bsp_in_USD' => 5000,
                'life_expectancy_m' => 64.1,
                'life_expectancy_w' => 68.5,
                'population_density' => 94,
                'country_iso_3' => 'KEN',
                'continent_iso_2' => 'AF',
                'continent_iso_3' => 'AFR',
                'country_visum_needed' => false,
                'country_visum_max_time' => null,
                'count_climatezones' => 3,
                'climatezones_ids' => '1,2,3',
                'climatezones_lnam' => 'Tropical, Savannah',
                'climatezones_details_lnam' => 'Kenya has a tropical climate with two rainy seasons.',
                'artikel' => 'das',
                'travelwarning_id' => null,
                'price_tendency' => 'Affordable',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Asien
            [
                'continent_id' => 3, // Asien
                'title' => 'Japan',
                'alias' => 'japan',
                'currency_code' => 'JPY',
                'currency_name' => 'Japanese Yen',
                'country_code' => 'JP',
                'country_text' => 'Japan is known for its advanced technology, rich culture, and beautiful landscapes.',
                'currency_conversion' => '0.007',
                'population' => 125360000,
                'capital' => 'Tokyo',
                'population_capital' => 37400000,
                'area' => 377972,
                'official_language' => 'Japanese',
                'language_ezmz' => 'Japanese',
                'bsp_in_USD' => 40000,
                'life_expectancy_m' => 81.3,
                'life_expectancy_w' => 87.5,
                'population_density' => 335,
                'country_iso_3' => 'JPN',
                'continent_iso_2' => 'AS',
                'continent_iso_3' => 'ASI',
                'country_visum_needed' => false,
                'country_visum_max_time' => null,
                'count_climatezones' => 3,
                'climatezones_ids' => '1,2,3',
                'climatezones_lnam' => 'Temperate, Subtropical',
                'climatezones_details_lnam' => 'Japan has a diverse climate ranging from temperate to subtropical.',
                'artikel' => 'das',
                'travelwarning_id' => null,
                'price_tendency' => 'Expensive',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'continent_id' => 3, // Asien
                'title' => 'India',
                'alias' => 'india',
                'currency_code' => 'INR',
                'currency_name' => 'Indian Rupee',
                'country_code' => 'IN',
                'country_text' => 'India is known for its rich history, diverse culture, and iconic landmarks.',
                'currency_conversion' => '0.012',
                'population' => 1393409038,
                'capital' => 'New Delhi',
                'population_capital' => 3152000,
                'area' => 3287263,
                'official_language' => 'Hindi, English',
                'language_ezmz' => 'Hindi',
                'bsp_in_USD' => 7000,
                'life_expectancy_m' => 69.8,
                'life_expectancy_w' => 72.2,
                'population_density' => 464,
                'country_iso_3' => 'IND',
                'continent_iso_2' => 'AS',
                'continent_iso_3' => 'ASI',
                'country_visum_needed' => false,
                'country_visum_max_time' => null,
                'count_climatezones' => 4,
                'climatezones_ids' => '1,2,3,4',
                'climatezones_lnam' => 'Tropical, Subtropical, Desert, Highland',
                'climatezones_details_lnam' => 'India has a diverse climate ranging from tropical to desert.',
                'artikel' => 'das',
                'travelwarning_id' => null,
                'price_tendency' => 'Affordable',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Nordamerika
            [
                'continent_id' => 5, // Nordamerika
                'title' => 'Canada',
                'alias' => 'canada',
                'currency_code' => 'CAD',
                'currency_name' => 'Canadian Dollar',
                'country_code' => 'CA',
                'country_text' => 'Canada is known for its vast landscapes, including forests, mountains, and lakes.',
                'currency_conversion' => '0.75',
                'population' => 38246108,
                'capital' => 'Ottawa',
                'population_capital' => 1430000,
                'area' => 9984670,
                'official_language' => 'English, French',
                'language_ezmz' => 'English',
                'bsp_in_USD' => 50000,
                'life_expectancy_m' => 81.2,
                'life_expectancy_w' => 84.5,
                'population_density' => 4,
                'country_iso_3' => 'CAN',
                'continent_iso_2' => 'NA',
                'continent_iso_3' => 'NAM',
                'country_visum_needed' => false,
                'country_visum_max_time' => null,
                'count_climatezones' => 4,
                'climatezones_ids' => '1,2,3,4',
                'climatezones_lnam' => 'Temperate, Subarctic, Arctic',
                'climatezones_details_lnam' => 'Canada has a diverse climate ranging from temperate to arctic.',
                'artikel' => 'das',
                'travelwarning_id' => null,
                'price_tendency' => 'Expensive',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Südamerika
            [
                'continent_id' => 7, // Südamerika
                'title' => 'Argentina',
                'alias' => 'argentina',
                'currency_code' => 'ARS',
                'currency_name' => 'Argentine Peso',
                'country_code' => 'AR',
                'country_text' => 'Argentina is known for its rich culture, tango, and Patagonia.',
                'currency_conversion' => '0.005',
                'population' => 45605823,
                'capital' => 'Buenos Aires',
                'population_capital' => 15590000,
                'area' => 2780400,
                'official_language' => 'Spanish',
                'language_ezmz' => 'Spanish',
                'bsp_in_USD' => 15000,
                'life_expectancy_m' => 73.5,
                'life_expectancy_w' => 79.8,
                'population_density' => 16,
                'country_iso_3' => 'ARG',
                'continent_iso_2' => 'SA',
                'continent_iso_3' => 'SAM',
                'country_visum_needed' => false,
                'country_visum_max_time' => null,
                'count_climatezones' => 3,
                'climatezones_ids' => '1,2,3',
                'climatezones_lnam' => 'Temperate, Subtropical',
                'climatezones_details_lnam' => 'Argentina has a diverse climate ranging from temperate to subtropical.',
                'artikel' => 'das',
                'travelwarning_id' => null,
                'price_tendency' => 'Medium',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Ozeanien
            [
                'continent_id' => 6, // Ozeanien
                'title' => 'Samoa',
                'alias' => 'samoa',
                'currency_code' => 'WST',
                'currency_name' => 'Samoan Tala',
                'country_code' => 'WS',
                'country_text' => 'Samoa is known for its beautiful beaches, rainforests, and traditional culture.',
                'currency_conversion' => '0.38',
                'population' => 200874,
                'capital' => 'Apia',
                'population_capital' => 37000,
                'area' => 2842,
                'official_language' => 'Samoan, English',
                'language_ezmz' => 'Samoan',
                'bsp_in_USD' => 6000,
                'life_expectancy_m' => 72.8,
                'life_expectancy_w' => 77.2,
                'population_density' => 71,
                'country_iso_3' => 'WSM',
                'continent_iso_2' => 'OC',
                'continent_iso_3' => 'OCE',
                'country_visum_needed' => false,
                'country_visum_max_time' => null,
                'count_climatezones' => 1,
                'climatezones_ids' => '1',
                'climatezones_lnam' => 'Tropical',
                'climatezones_details_lnam' => 'Samoa has a tropical climate with warm temperatures year-round.',
                'artikel' => 'das',
                'travelwarning_id' => null,
                'price_tendency' => 'Affordable',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Afrika
            [
                'continent_id' => 1, // Afrika
                'title' => 'Nigeria',
                'alias' => 'nigeria',
                'currency_code' => 'NGN',
                'currency_name' => 'Naira',
                'country_code' => 'NG',
                'country_text' => 'Nigeria is the most populous country in Africa and known for its diverse culture and oil industry.',
                'currency_conversion' => '0.0022',
                'population' => 211400708,
                'capital' => 'Abuja',
                'population_capital' => 3560000,
                'area' => 923768,
                'official_language' => 'English',
                'language_ezmz' => 'English',
                'bsp_in_USD' => 6000,
                'life_expectancy_m' => 54.5,
                'life_expectancy_w' => 56.5,
                'population_density' => 229,
                'country_iso_3' => 'NGA',
                'continent_iso_2' => 'AF',
                'continent_iso_3' => 'AFR',
                'country_visum_needed' => false,
                'country_visum_max_time' => null,
                'count_climatezones' => 2,
                'climatezones_ids' => '1,2',
                'climatezones_lnam' => 'Tropical, Savannah',
                'climatezones_details_lnam' => 'Nigeria has a tropical climate with two distinct seasons.',
                'artikel' => 'das',
                'travelwarning_id' => null,
                'price_tendency' => 'Affordable',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'continent_id' => 1, // Afrika
                'title' => 'Ethiopia',
                'alias' => 'ethiopia',
                'currency_code' => 'ETB',
                'currency_name' => 'Birr',
                'country_code' => 'ET',
                'country_text' => 'Ethiopia is known for its ancient history, unique culture, and coffee production.',
                'currency_conversion' => '0.018',
                'population' => 126527000,
                'capital' => 'Addis Ababa',
                'population_capital' => 3384000,
                'area' => 1104300,
                'official_language' => 'Amharic',
                'language_ezmz' => 'Amharic',
                'bsp_in_USD' => 2000,
                'life_expectancy_m' => 64.5,
                'life_expectancy_w' => 68.5,
                'population_density' => 115,
                'country_iso_3' => 'ETH',
                'continent_iso_2' => 'AF',
                'continent_iso_3' => 'AFR',
                'country_visum_needed' => false,
                'country_visum_max_time' => null,
                'count_climatezones' => 3,
                'climatezones_ids' => '1,2,3',
                'climatezones_lnam' => 'Tropical, Highland',
                'climatezones_details_lnam' => 'Ethiopia has a diverse climate with highlands and tropical regions.',
                'artikel' => 'das',
                'travelwarning_id' => null,
                'price_tendency' => 'Affordable',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Asien
            [
                'continent_id' => 3, // Asien
                'title' => 'South Korea',
                'alias' => 'south-korea',
                'currency_code' => 'KRW',
                'currency_name' => 'South Korean Won',
                'country_code' => 'KR',
                'country_text' => 'South Korea is known for its high-tech industry, K-pop, and vibrant culture.',
                'currency_conversion' => '0.00075',
                'population' => 51780579,
                'capital' => 'Seoul',
                'population_capital' => 9776000,
                'area' => 100210,
                'official_language' => 'Korean',
                'language_ezmz' => 'Korean',
                'bsp_in_USD' => 35000,
                'life_expectancy_m' => 82.3,
                'life_expectancy_w' => 88.5,
                'population_density' => 517,
                'country_iso_3' => 'KOR',
                'continent_iso_2' => 'AS',
                'continent_iso_3' => 'ASI',
                'country_visum_needed' => false,
                'country_visum_max_time' => null,
                'count_climatezones' => 2,
                'climatezones_ids' => '1,2',
                'climatezones_lnam' => 'Temperate, Subtropical',
                'climatezones_details_lnam' => 'South Korea has a temperate climate with four distinct seasons.',
                'artikel' => 'das',
                'travelwarning_id' => null,
                'price_tendency' => 'Expensive',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'continent_id' => 3, // Asien
                'title' => 'Thailand',
                'alias' => 'thailand',
                'currency_code' => 'THB',
                'currency_name' => 'Thai Baht',
                'country_code' => 'TH',
                'country_text' => 'Thailand is known for its beautiful beaches, rich culture, and delicious cuisine.',
                'currency_conversion' => '0.028',
                'population' => 71601103,
                'capital' => 'Bangkok',
                'population_capital' => 10539000,
                'area' => 513120,
                'official_language' => 'Thai',
                'language_ezmz' => 'Thai',
                'bsp_in_USD' => 15000,
                'life_expectancy_m' => 74.9,
                'life_expectancy_w' => 79.8,
                'population_density' => 140,
                'country_iso_3' => 'THA',
                'continent_iso_2' => 'AS',
                'continent_iso_3' => 'ASI',
                'country_visum_needed' => false,
                'country_visum_max_time' => null,
                'count_climatezones' => 2,
                'climatezones_ids' => '1,2',
                'climatezones_lnam' => 'Tropical, Subtropical',
                'climatezones_details_lnam' => 'Thailand has a tropical climate with a rainy season.',
                'artikel' => 'das',
                'travelwarning_id' => null,
                'price_tendency' => 'Affordable',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Europa
            [
                'continent_id' => 4, // Europa
                'title' => 'Italy',
                'alias' => 'italy',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'country_code' => 'IT',
                'country_text' => 'Italy is known for its rich history, art, and delicious cuisine.',
                'currency_conversion' => '1.0',
                'population' => 59077417,
                'capital' => 'Rome',
                'population_capital' => 2870000,
                'area' => 301340,
                'official_language' => 'Italian',
                'language_ezmz' => 'Italian',
                'bsp_in_USD' => 35000,
                'life_expectancy_m' => 81.3,
                'life_expectancy_w' => 85.5,
                'population_density' => 196,
                'country_iso_3' => 'ITA',
                'continent_iso_2' => 'EU',
                'continent_iso_3' => 'EUR',
                'country_visum_needed' => false,
                'country_visum_max_time' => null,
                'count_climatezones' => 3,
                'climatezones_ids' => '1,2,3',
                'climatezones_lnam' => 'Temperate, Mediterranean',
                'climatezones_details_lnam' => 'Italy has a diverse climate with both temperate and Mediterranean regions.',
                'artikel' => 'das',
                'travelwarning_id' => null,
                'price_tendency' => 'Medium',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'continent_id' => 4, // Europa
                'title' => 'Sweden',
                'alias' => 'sweden',
                'currency_code' => 'SEK',
                'currency_name' => 'Swedish Krona',
                'country_code' => 'SE',
                'country_text' => 'Sweden is known for its stunning nature, high standard of living, and social welfare system.',
                'currency_conversion' => '0.095',
                'population' => 10353442,
                'capital' => 'Stockholm',
                'population_capital' => 975000,
                'area' => 450295,
                'official_language' => 'Swedish',
                'language_ezmz' => 'Swedish',
                'bsp_in_USD' => 55000,
                'life_expectancy_m' => 81.5,
                'life_expectancy_w' => 85.3,
                'population_density' => 23,
                'country_iso_3' => 'SWE',
                'continent_iso_2' => 'EU',
                'continent_iso_3' => 'EUR',
                'country_visum_needed' => false,
                'country_visum_max_time' => null,
                'count_climatezones' => 2,
                'climatezones_ids' => '1,2',
                'climatezones_lnam' => 'Temperate, Subarctic',
                'climatezones_details_lnam' => 'Sweden has a temperate climate in the south and subarctic in the north.',
                'artikel' => 'das',
                'travelwarning_id' => null,
                'price_tendency' => 'Expensive',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Nordamerika
            [
                'continent_id' => 5, // Nordamerika
                'title' => 'Mexico',
                'alias' => 'mexico',
                'currency_code' => 'MXN',
                'currency_name' => 'Mexican Peso',
                'country_code' => 'MX',
                'country_text' => 'Mexico is known for its rich history, vibrant culture, and beautiful beaches.',
                'currency_conversion' => '0.055',
                'population' => 127575529,
                'capital' => 'Mexico City',
                'population_capital' => 8855000,
                'area' => 1964375,
                'official_language' => 'Spanish',
                'language_ezmz' => 'Spanish',
                'bsp_in_USD' => 18000,
                'life_expectancy_m' => 74.5,
                'life_expectancy_w' => 79.8,
                'population_density' => 65,
                'country_iso_3' => 'MEX',
                'continent_iso_2' => 'NA',
                'continent_iso_3' => 'NAM',
                'country_visum_needed' => false,
                'country_visum_max_time' => null,
                'count_climatezones' => 3,
                'climatezones_ids' => '1,2,3',
                'climatezones_lnam' => 'Tropical, Subtropical',
                'climatezones_details_lnam' => 'Mexico has a diverse climate ranging from tropical to subtropical.',
                'artikel' => 'das',
                'travelwarning_id' => null,
                'price_tendency' => 'Affordable',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Südamerika
            [
                'continent_id' => 7, // Südamerika
                'title' => 'Chile',
                'alias' => 'chile',
                'currency_code' => 'CLP',
                'currency_name' => 'Chilean Peso',
                'country_code' => 'CL',
                'country_text' => 'Chile is known for its long coastline, diverse landscapes, and wine production.',
                'currency_conversion' => '0.0012',
                'population' => 19107216,
                'capital' => 'Santiago',
                'population_capital' => 7112808,
                'area' => 756102,
                'official_language' => 'Spanish',
                'language_ezmz' => 'Spanish',
                'bsp_in_USD' => 20000,
                'life_expectancy_m' => 78.5,
                'life_expectancy_w' => 82.5,
                'population_density' => 25,
                'country_iso_3' => 'CHL',
                'continent_iso_2' => 'SA',
                'continent_iso_3' => 'SAM',
                'country_visum_needed' => false,
                'country_visum_max_time' => null,
                'count_climatezones' => 3,
                'climatezones_ids' => '1,2,3',
                'climatezones_lnam' => 'Temperate, Desert',
                'climatezones_details_lnam' => 'Chile has a diverse climate ranging from temperate to desert.',
                'artikel' => 'das',
                'travelwarning_id' => null,
                'price_tendency' => 'Medium',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Ozeanien
            [
                'continent_id' => 6, // Ozeanien
                'title' => 'Tonga',
                'alias' => 'tonga',
                'currency_code' => 'TOP',
                'currency_name' => 'Tongan Paʻanga',
                'country_code' => 'TO',
                'country_text' => 'Tonga is known for its beautiful islands, coral reefs, and traditional culture.',
                'currency_conversion' => '0.42',
                'population' => 106017,
                'capital' => 'Nukuʻalofa',
                'population_capital' => 23658,
                'area' => 747,
                'official_language' => 'Tongan, English',
                'language_ezmz' => 'Tongan',
                'bsp_in_USD' => 5000,
                'life_expectancy_m' => 72.5,
                'life_expectancy_w' => 76.5,
                'population_density' => 142,
                'country_iso_3' => 'TON',
                'continent_iso_2' => 'OC',
                'continent_iso_3' => 'OCE',
                'country_visum_needed' => false,
                'country_visum_max_time' => null,
                'count_climatezones' => 1,
                'climatezones_ids' => '1',
                'climatezones_lnam' => 'Tropical',
                'climatezones_details_lnam' => 'Tonga has a tropical climate with warm temperatures year-round.',
                'artikel' => 'das',
                'travelwarning_id' => null,
                'price_tendency' => 'Affordable',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Asien (China)
            [
                'continent_id' => 3, // Asien
                'title' => 'China',
                'alias' => 'china',
                'currency_code' => 'CNY',
                'currency_name' => 'Chinese Yuan',
                'country_code' => 'CN',
                'country_text' => 'China is the most populous country in the world, known for its rich history, culture, and rapid economic growth.',
                'currency_conversion' => '0.15',
                'population' => 1402112000,
                'capital' => 'Beijing',
                'population_capital' => 21710000,
                'area' => 9596961,
                'official_language' => 'Mandarin',
                'language_ezmz' => 'Mandarin',
                'bsp_in_USD' => 12000,
                'life_expectancy_m' => 75.6,
                'life_expectancy_w' => 78.2,
                'population_density' => 146,
                'country_iso_3' => 'CHN',
                'continent_iso_2' => 'AS',
                'continent_iso_3' => 'ASI',
                'country_visum_needed' => true,
                'country_visum_max_time' => 30,
                'count_climatezones' => 5,
                'climatezones_ids' => '1,2,3,4,5',
                'climatezones_lnam' => 'Tropical, Subtropical, Temperate, Desert, Highland',
                'climatezones_details_lnam' => 'China has a diverse climate due to its vast size, ranging from tropical in the south to subarctic in the north.',
                'artikel' => 'das',
                'travelwarning_id' => null,
                'price_tendency' => 'Moderate',
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);
    }
}
