<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WwdeCountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('wwde_countries')->insert([
            [
                'continent_id' => 3, // Europa
                'title' => 'Germany',
                'alias' => 'germany',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'country_code' => 'DE',
                'country_text' => 'Germany is a country in central Europe known for its rich history and culture.',
                'currency_conversion' => '1.0',
                'population' => 83166711,
                'capital' => 'Berlin',
                'population_capital' => 3644826,
                'area' => 357022,
                'official_language' => 'German',
                'language_ezmz' => 'German',
                'bsp_in_USD' => 45000,
                'life_expectancy_m' => 78.6,
                'life_expectancy_w' => 83.4,
                'population_density' => 233,
                'country_iso_3' => 'DEU',
                'continent_iso_2' => 'EU',
                'continent_iso_3' => 'EUR',
                'country_visum_needed' => false,
                'country_visum_max_time' => null,
                'count_climatezones' => 1,
                'climatezones_ids' => '1',
                'climatezones_lnam' => 'Temperate',
                'climatezones_details_lnam' => 'Moderate climate zone with cold winters and mild summers.',
                'artikel' => 'das',
                'travelwarning_id' => null,
                'price_tendency' => 'Medium',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'continent_id' => 3, // Europa
                'title' => 'France',
                'alias' => 'france',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'country_code' => 'FR',
                'country_text' => 'France is known for its art, cuisine, and iconic landmarks like the Eiffel Tower.',
                'currency_conversion' => '1.0',
                'population' => 67413000,
                'capital' => 'Paris',
                'population_capital' => 2140526,
                'area' => 551695,
                'official_language' => 'French',
                'language_ezmz' => 'French',
                'bsp_in_USD' => 41000,
                'life_expectancy_m' => 79.5,
                'life_expectancy_w' => 85.3,
                'population_density' => 122,
                'country_iso_3' => 'FRA',
                'continent_iso_2' => 'EU',
                'continent_iso_3' => 'EUR',
                'country_visum_needed' => false,
                'country_visum_max_time' => null,
                'count_climatezones' => 3,
                'climatezones_ids' => '1,2,3',
                'climatezones_lnam' => 'Temperate, Mediterranean',
                'climatezones_details_lnam' => 'Diverse climate zones with both temperate and Mediterranean regions.',
                'artikel' => 'das',
                'travelwarning_id' => null,
                'price_tendency' => 'Medium',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'continent_id' => 1, // Afrika
                'title' => 'South Africa',
                'alias' => 'south-africa',
                'currency_code' => 'ZAR',
                'currency_name' => 'Rand',
                'country_code' => 'ZA',
                'country_text' => 'South Africa is known for its diverse cultures, wildlife, and stunning landscapes.',
                'currency_conversion' => '0.06',
                'population' => 59308690,
                'capital' => 'Pretoria',
                'population_capital' => 741651,
                'area' => 1219090,
                'official_language' => '11 official languages',
                'language_ezmz' => 'English, Zulu, Afrikaans, others',
                'bsp_in_USD' => 12000,
                'life_expectancy_m' => 64.3,
                'life_expectancy_w' => 68.1,
                'population_density' => 49,
                'country_iso_3' => 'ZAF',
                'continent_iso_2' => 'AF',
                'continent_iso_3' => 'AFR',
                'country_visum_needed' => false,
                'country_visum_max_time' => null,
                'count_climatezones' => 4,
                'climatezones_ids' => '1,2,3,4',
                'climatezones_lnam' => 'Desert, Mediterranean, Subtropical, Temperate',
                'climatezones_details_lnam' => 'Diverse climate zones including deserts and subtropical regions.',
                'artikel' => 'das',
                'travelwarning_id' => null,
                'price_tendency' => 'Affordable',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'continent_id' => 5, // Nordamerika
                'title' => 'United States',
                'alias' => 'united-states',
                'currency_code' => 'USD',
                'currency_name' => 'Dollar',
                'country_code' => 'US',
                'country_text' => 'The United States is a country known for its global influence and diverse landscapes.',
                'currency_conversion' => '1.0',
                'population' => 331893745,
                'capital' => 'Washington, D.C.',
                'population_capital' => 692683,
                'area' => 9833520,
                'official_language' => 'English',
                'language_ezmz' => 'English',
                'bsp_in_USD' => 63000,
                'life_expectancy_m' => 76.3,
                'life_expectancy_w' => 81.4,
                'population_density' => 36,
                'country_iso_3' => 'USA',
                'continent_iso_2' => 'NA',
                'continent_iso_3' => 'NAM',
                'country_visum_needed' => true,
                'country_visum_max_time' => 90,
                'count_climatezones' => 6,
                'climatezones_ids' => '1,2,3,4,5,6',
                'climatezones_lnam' => 'Desert, Mediterranean, Subtropical, Temperate, Continental, Polar',
                'climatezones_details_lnam' => 'Wide range of climates from deserts to polar regions.',
                'artikel' => 'die',
                'travelwarning_id' => null,
                'price_tendency' => 'Expensive',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'continent_id' => 4, // Südamerika
                'title' => 'Brazil',
                'alias' => 'brazil',
                'currency_code' => 'BRL',
                'currency_name' => 'Real',
                'country_code' => 'BR',
                'country_text' => 'Brazil is known for its vibrant culture, Amazon rainforest, and beautiful beaches.',
                'currency_conversion' => '0.18',
                'population' => 213993437,
                'capital' => 'Brasília',
                'population_capital' => 3055149,
                'area' => 8515767,
                'official_language' => 'Portuguese',
                'language_ezmz' => 'Portuguese',
                'bsp_in_USD' => 7200,
                'life_expectancy_m' => 72.8,
                'life_expectancy_w' => 79.9,
                'population_density' => 25,
                'country_iso_3' => 'BRA',
                'continent_iso_2' => 'SA',
                'continent_iso_3' => 'SAM',
                'country_visum_needed' => false,
                'country_visum_max_time' => 90,
                'count_climatezones' => 5,
                'climatezones_ids' => '1,2,3,4,5',
                'climatezones_lnam' => 'Tropical, Subtropical, Desert, Savanna, Temperate',
                'climatezones_details_lnam' => 'Mostly tropical with diverse ecosystems.',
                'artikel' => 'das',
                'travelwarning_id' => null,
                'price_tendency' => 'Affordable',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'continent_id' => 6, // Ozeanien
                'title' => 'Australia',
                'alias' => 'australia',
                'currency_code' => 'AUD',
                'currency_name' => 'Australian Dollar',
                'country_code' => 'AU',
                'country_text' => 'Australia is known for its unique wildlife, stunning landscapes, and vibrant cities like Sydney and Melbourne.',
                'currency_conversion' => '0.65', // Beispiel-Wechselkurs
                'population' => 25788217,
                'capital' => 'Canberra',
                'population_capital' => 451000,
                'area' => 7692024,
                'official_language' => 'English',
                'language_ezmz' => 'English',
                'bsp_in_USD' => 50000,
                'life_expectancy_m' => 81.2,
                'life_expectancy_w' => 85.0,
                'population_density' => 3,
                'country_iso_3' => 'AUS',
                'continent_iso_2' => 'OC',
                'continent_iso_3' => 'OCE',
                'country_visum_needed' => false,
                'country_visum_max_time' => null,
                'count_climatezones' => 4,
                'climatezones_ids' => '1,2,3,4',
                'climatezones_lnam' => 'Tropical, Subtropical, Temperate, Arid',
                'climatezones_details_lnam' => 'Australia has a diverse range of climates, from tropical rainforests to arid deserts.',
                'artikel' => 'das',
                'travelwarning_id' => null,
                'price_tendency' => 'Medium',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'continent_id' => 6, // Ozeanien
                'title' => 'New Zealand',
                'alias' => 'new-zealand',
                'currency_code' => 'NZD',
                'currency_name' => 'New Zealand Dollar',
                'country_code' => 'NZ',
                'country_text' => 'New Zealand is famous for its breathtaking landscapes, including mountains, fiords, and geothermal areas.',
                'currency_conversion' => '0.60', // Beispiel-Wechselkurs
                'population' => 5132700,
                'capital' => 'Wellington',
                'population_capital' => 215000,
                'area' => 268021,
                'official_language' => 'English, Māori, New Zealand Sign Language',
                'language_ezmz' => 'English, Māori',
                'bsp_in_USD' => 40000,
                'life_expectancy_m' => 80.5,
                'life_expectancy_w' => 84.3,
                'population_density' => 18,
                'country_iso_3' => 'NZL',
                'continent_iso_2' => 'OC',
                'continent_iso_3' => 'OCE',
                'country_visum_needed' => false,
                'country_visum_max_time' => null,
                'count_climatezones' => 3,
                'climatezones_ids' => '1,2,3',
                'climatezones_lnam' => 'Temperate, Subtropical, Oceanic',
                'climatezones_details_lnam' => 'New Zealand has a mild, temperate climate with a variety of microclimates.',
                'artikel' => 'das',
                'travelwarning_id' => null,
                'price_tendency' => 'Medium',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'continent_id' => 6, // Ozeanien
                'title' => 'Fiji',
                'alias' => 'fiji',
                'currency_code' => 'FJD',
                'currency_name' => 'Fijian Dollar',
                'country_code' => 'FJ',
                'country_text' => 'Fiji is known for its stunning beaches, coral reefs, and friendly locals.',
                'currency_conversion' => '0.45', // Beispiel-Wechselkurs
                'population' => 926276,
                'capital' => 'Suva',
                'population_capital' => 177000,
                'area' => 18274,
                'official_language' => 'English, Fijian, Hindi',
                'language_ezmz' => 'English, Fijian',
                'bsp_in_USD' => 9000,
                'life_expectancy_m' => 69.8,
                'life_expectancy_w' => 73.6,
                'population_density' => 49,
                'country_iso_3' => 'FJI',
                'continent_iso_2' => 'OC',
                'continent_iso_3' => 'OCE',
                'country_visum_needed' => false,
                'country_visum_max_time' => null,
                'count_climatezones' => 2,
                'climatezones_ids' => '1,2',
                'climatezones_lnam' => 'Tropical, Subtropical',
                'climatezones_details_lnam' => 'Fiji has a tropical climate with warm temperatures year-round.',
                'artikel' => 'das',
                'travelwarning_id' => null,
                'price_tendency' => 'Affordable',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'continent_id' => 6, // Ozeanien
                'title' => 'Papua New Guinea',
                'alias' => 'papua-new-guinea',
                'currency_code' => 'PGK',
                'currency_name' => 'Papua New Guinean Kina',
                'country_code' => 'PG',
                'country_text' => 'Papua New Guinea is known for its diverse cultures, rainforests, and rugged terrain.',
                'currency_conversion' => '0.28', // Beispiel-Wechselkurs
                'population' => 9119000,
                'capital' => 'Port Moresby',
                'population_capital' => 364125,
                'area' => 462840,
                'official_language' => 'English',
                'language_ezmz' => 'English',
                'bsp_in_USD' => 2500,
                'life_expectancy_m' => 63.2,
                'life_expectancy_w' => 65.8,
                'population_density' => 19,
                'country_iso_3' => 'PNG',
                'continent_iso_2' => 'OC',
                'continent_iso_3' => 'OCE',
                'country_visum_needed' => true,
                'country_visum_max_time' => 30,
                'count_climatezones' => 3,
                'climatezones_ids' => '1,2,3',
                'climatezones_lnam' => 'Tropical, Subtropical, Highland',
                'climatezones_details_lnam' => 'Papua New Guinea has a tropical climate with high humidity and rainfall.',
                'artikel' => 'das',
                'travelwarning_id' => null,
                'price_tendency' => 'Affordable',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
